services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: edfer
      POSTGRES_PASSWORD: oZB9h8pYT3rLWxDCr6VZME9tZQcbBfdv
      POSTGRES_DB: socialnetwork
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U edfer -d socialnetwork"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    command: npm run dev
    ports:
      - "3005:3005"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
